### ISSUE TITLE
Add a ?help command

### ISSUE THREAD

**Issue by ghost** [M-Davies/oghma#6]
Right now, all the commands have limited help text attached to them depending on how much info you offer to the command. However, a generalised help command would be a useful addition as I feel like every bot would need one. This command could offer stuff like:
- The list of commands and examples of them executing
- Where to open issues if things go wrong
- Other info that's relevant to a `?help` command

**Comment by EmadDeve20** [comment]
hi shadowedlucario. I liked Your repo and nice.
I want to cooperate. Can you tell me where to start reading your code?
If you wish

**Comment by ghost** [comment]
Fixed by https://github.com/shadowedlucario/oghma/pull/16
